# Generated by Django 4.2.5 on 2023-09-09 00:49

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 존재하는 닉네임입니다'}, max_length=15, null=True, unique=True, validators=[user.validators.validate_no_special_characters]),
        ),
    ]
